//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGADuel
{
    using System;
    using System.Collections.Generic;
    
    public partial class recordinfo
    {
        public int RecordID { get; set; }
        public Nullable<int> RecordTypeID { get; set; }
        public string RecordUser { get; set; }
        public string RecordHero { get; set; }
        public Nullable<int> RecordServer { get; set; }
        public string RecordData { get; set; }
        public string RecordImage { get; set; }
    }
}
